import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=id=>document.getElementById(id);
const S={started:false,fuse:false,key:false,doll:false,won:false,dead:false,fear:10,battery:100,flash:true,run:false,stamina:100,chapter:0,lastScare:0,entityMode:'hidden'};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050403);scene.fog=new THREE.FogExp2(0x090705,.035);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,80);camera.position.set(0,1.65,9);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const mats={wall:new THREE.MeshStandardMaterial({color:0x25211d,roughness:1}),wood:new THREE.MeshStandardMaterial({color:0x29170f,roughness:.9}),floor:new THREE.MeshStandardMaterial({color:0x17100c,roughness:1}),trim:new THREE.MeshStandardMaterial({color:0x0b0908,roughness:1}),metal:new THREE.MeshStandardMaterial({color:0xb7b5ad,metalness:.55,roughness:.35}),gold:new THREE.MeshStandardMaterial({color:0xb99b50,metalness:.4,roughness:.35}),cloth:new THREE.MeshStandardMaterial({color:0x332723,roughness:1}),black:new THREE.MeshStandardMaterial({color:0x030303,roughness:1})};
const interactables=[];const colliders=[];const lights=[];
function box(name,x,y,z,w,h,d,mat,solid=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.name=name;m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(solid)colliders.push({x,y,z,w,h,d});return m}
function room(z,w=7,d=7){box('floor',0,-.1,z,w,.2,d,mats.floor);box('ceiling',0,3.55,z,w,.2,d,mats.trim);box('wallL',-w/2,1.75,z,.18,3.5,d,mats.wall,true);box('wallR',w/2,1.75,z,.18,3.5,d,mats.wall,true);box('back',0,1.75,z+d/2,w,3.5,.18,mats.wall,true)}
room(7,7,7);room(0,7,7);room(-7,7,7);room(-14,9,7);room(-21,9,7);
// Open doorways connect the rooms; furniture gives the house readable landmarks.
function doorway(z,x=0,w=2.4){box('frame',x,2.7,z,w+.35,.25,.35,mats.wood);box('jambL',x-w/2,1.4,z,.22,2.8,.35,mats.wood);box('jambR',x+w/2,1.4,z,.22,2.8,.35,mats.wood)}
doorway(3.5);doorway(-3.5);doorway(-10.5);doorway(-17.5,0,3.2);
for(const z of [7,0,-7,-14,-21]){const l=new THREE.PointLight(0xd7b37a,1.35,6.5);l.position.set(0,3.05,z);l.castShadow=true;l.shadow.mapSize.set(256,256);scene.add(l);lights.push(l);box('bulb',0,3.08,z,.12,.12,.12,new THREE.MeshBasicMaterial({color:0xffdfaa}));}
// Props
box('sofa',-2.1,.7,4.8,2.2,1.25,1.1,mats.cloth,true);box('cabinet',2.25,1.2,1.1,1.1,2.4,.65,mats.wood,true);box('table',-2.1,.65,-2.2,2.3,1.1,1.15,mats.wood,true);box('wardrobe',2.15,1.45,-8.5,1.3,2.9,.8,mats.wood,true);box('bed',-2.0,.55,-15.4,3.2,.8,2.1,mats.cloth,true);box('desk',2.2,.75,-19.3,2.1,1.4,.8,mats.wood,true);box('mirror',-3.8,1.7,-19.7,.08,2.2,1.2,new THREE.MeshStandardMaterial({color:0x22272a,metalness:.7,roughness:.2}));
function item(name,p,mat,kind){const o=box(name,p[0],p[1],p[2],.42,.42,.28,mat);o.userData.kind=kind;interactables.push(o);return o}
const fuse=item('fuse',[2.2,1.7,5.3],mats.metal,'fuse');const key=item('key',[-2.1,1.25,-2.2],mats.gold,'key');const doll=item('doll',[2.1,.75,-13.8],mats.cloth,'doll');
key.visible=false;doll.visible=false;
const exit=box('exit',0,1.5,-24.45,2.2,2.9,.2,mats.trim);exit.userData.kind='exit';interactables.push(exit);
// A simple but readable Watcher silhouette.
const watcher=new THREE.Group();watcher.position.set(0,0,-10);const wb=box('watcherBody',0,1.25,0,.8,2.35,.52,mats.black);wb.parent=watcher;const head=new THREE.Mesh(new THREE.SphereGeometry(.39,16,12),mats.black);head.position.set(0,2.55,0);watcher.add(head);for(const x of [-.14,.14]){const e=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),new THREE.MeshBasicMaterial({color:0xffffff}));e.position.set(x,2.62,-.35);watcher.add(e)}scene.add(watcher);watcher.visible=false;
const flashlight=new THREE.SpotLight(0xfff4dc,5.5,18,Math.PI/7,.5,1.3);camera.add(flashlight);camera.add(flashlight.target);scene.add(camera);scene.add(new THREE.HemisphereLight(0x4d4740,0x050403,.38));
const keys={};const joy={x:0,y:0};let yaw=0,pitch=0,last=performance.now(),look=null,scareCooldown=0;
function hud(){const f=Math.round(S.fear);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=Math.round(S.battery)+'%';$('objective').textContent=!S.fuse?'Find the fuse in the living room.':!S.key?'The house moved. Find the key.':!S.doll?'Something is watching. Find the doll.':'Get to the front door.';$('inventory').textContent=S.doll?'WATCHER DOLL':S.key?'HOUSE KEY':S.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',S.fuse],['checkKey',S.key],['checkDoll',S.doll],['checkEscape',S.won]].forEach(([i,v])=>$(i)?.classList.toggle('done',v))}
function say(t){$('status').textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>{$('status').textContent='READY'},2400)}
function start(){if(S.started)return;S.started=true;$('boot').classList.add('hidden');say('The front door locks behind you. Find the fuse.');hud();}
window.startGame=start;$('startBtn').addEventListener('click',start);$('startBtn').addEventListener('pointerup',e=>{e.preventDefault();start()});
function blocked(x,z){if(x<-3.25||x>3.25)return true;for(const c of colliders){if(c.name==='wallL'||c.name==='wallR')continue;const ax=c.x-c.w/2-.35,bx=c.x+c.w/2+.35,az=c.z-c.d/2-.35,bz=c.z+c.d/2+.35;if(x>ax&&x<bx&&z>az&&z<bz)return true}return false}
function move(dt){if(!S.started||S.dead||S.won)return;let x=(keys.a?-1:0)+(keys.d?1:0)+joy.x,z=(keys.w?-1:0)+(keys.s?1:0)+joy.y;if(!x&&!z)return;const n=Math.hypot(x,z);const sprint=S.run&&S.stamina>2;const v=(sprint?3.7:2.15)*dt;if(sprint)S.stamina=Math.max(0,S.stamina-dt*25);else S.stamina=Math.min(100,S.stamina+dt*14);const dx=(Math.cos(yaw)*x/n+Math.sin(yaw)*z/n)*v,dz=(-Math.sin(yaw)*x/n+Math.cos(yaw)*z/n)*v;const nx=camera.position.x+dx,nz=camera.position.z+dz;if(!blocked(nx,camera.position.z))camera.position.x=nx;if(!blocked(camera.position.x,nz))camera.position.z=nz}
function collect(o){const k=o.userData.kind;if(k==='fuse'&&!S.fuse){S.fuse=true;o.visible=false;S.chapter=1;S.fear+=10;key.visible=true;watcher.visible=true;watcher.position.set(-2,0,0);say('POWER RESTORED. You heard footsteps upstairs.')}else if(k==='key'&&S.fuse&&!S.key){S.key=true;o.visible=false;S.chapter=2;S.fear+=12;doll.visible=true;watcher.visible=false;say('The key was not here a moment ago.')}else if(k==='doll'&&S.key&&!S.doll){S.doll=true;o.visible=false;S.chapter=3;S.fear+=22;watcher.visible=true;watcher.position.set(0,0,-18);say('DO NOT LOOK BACK. RUN TO THE FRONT DOOR.')}else if(k==='exit'&&S.fuse&&S.key&&S.doll){S.won=true;$('win').classList.remove('hidden');say('YOU ESCAPED. THE HOUSE REMEMBERS.')}else if(k==='exit')say('The lock will not move.');hud()}
function interact(){if(!S.started||S.dead||S.won)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects(interactables,false);const h=hits.find(v=>v.distance<3.2);if(!h){say('Nothing within reach.');return}collect(h.object)}
function toggleLight(){if(!S.started||S.dead)return;S.flash=!S.flash;flashlight.intensity=S.flash?5.5:0;say(S.flash?'Flashlight on.':'Flashlight off.')} 
function watcherAI(dt,now){if(!watcher.visible)return;const dx=camera.position.x-watcher.position.x,dz=camera.position.z-watcher.position.z,dist=Math.hypot(dx,dz);watcher.lookAt(camera.position.x,1.4,camera.position.z);if(S.chapter<3){if(dist<4.5&&now-scareCooldown>5000){S.fear=Math.min(100,S.fear+9);scareCooldown=now;say('Something moved behind you.');}return}const speed=S.run?1.0:1.35;const step=Math.min(dist,dt*speed);if(dist>2) {watcher.position.x+=dx/dist*step;watcher.position.z+=dz/dist*step;}if(dist<2.1){S.fear=Math.min(100,S.fear+dt*10);if(dist<1.05){S.dead=true;$('death').classList.remove('hidden');say('IT FOUND YOU.')}}}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(S.started&&!S.dead&&!S.won){move(dt);if(S.flash)S.battery=Math.max(0,S.battery-dt*.72);if(S.fuse)S.fear=Math.min(100,S.fear+dt*.012);watcherAI(dt,now);if(S.fear>=100){S.dead=true;$('death').classList.remove('hidden')}}flashlight.position.copy(camera.position);flashlight.target.position.copy(camera.position).add(new THREE.Vector3(-Math.sin(yaw),-.08,-Math.cos(yaw)).multiplyScalar(5));hud();renderer.render(scene,camera);requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k==='f')toggleLight();if(k==='e'||e.key==='enter')interact();if(k==='shift')S.run=true});window.addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys[k]=false;if(k==='shift')S.run=false});
function bind(id,x,y){const b=$(id);if(!b)return;const on=e=>{e.preventDefault();joy.x=x;joy.y=y};const off=e=>{e.preventDefault();joy.x=0;joy.y=0};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)}bind('up',0,-1);bind('down',0,1);bind('left',-1,0);bind('right',1,0);$('lightBtn')?.addEventListener('click',toggleLight);$('interactBtn')?.addEventListener('click',interact);$('runBtn')?.addEventListener('pointerdown',()=>S.run=true);['pointerup','pointercancel','pointerleave'].forEach(e=>$('runBtn')?.addEventListener(e,()=>S.run=false));$('retryBtn')?.addEventListener('click',()=>location.reload());$('againBtn')?.addEventListener('click',()=>location.reload());
renderer.domElement.addEventListener('pointerdown',e=>{if(!S.started||e.target.closest('button'))return;look={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!look)return;yaw-=(e.clientX-look.x)*.004;pitch-=(e.clientY-look.y)*.004;pitch=Math.max(-1.25,Math.min(1.25,pitch));camera.rotation.set(pitch,yaw,0);look={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',()=>look=null);renderer.domElement.addEventListener('pointercancel',()=>look=null);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});hud();requestAnimationFrame(frame);