import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id);
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<800;
const g={start:false,fuse:false,key:false,doll:false,win:false,dead:false,light:true,battery:100,run:false,stamina:100,fear:8,zone:0};
const keys={};const joy={x:0,y:0};let yaw=0,pitch=0,look=null,last=performance.now(),lastHud=0,lastAi=0,shake=0;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020202);scene.fog=new THREE.FogExp2(0x080706,.045);
const cam=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,70);cam.position.set(0,1.62,8.2);cam.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.BasicShadowMap;$('scene').appendChild(renderer.domElement);
const W=new THREE.MeshStandardMaterial({color:0x28221c,roughness:1}),F=new THREE.MeshStandardMaterial({color:0x120d09,roughness:1}),D=new THREE.MeshStandardMaterial({color:0x090807,roughness:1}),WOOD=new THREE.MeshStandardMaterial({color:0x38200f,roughness:.92}),METAL=new THREE.MeshStandardMaterial({color:0xb9b5a8,metalness:.35,roughness:.45}),GOLD=new THREE.MeshStandardMaterial({color:0xc89d3d,metalness:.55,roughness:.3}),BLACK=new THREE.MeshStandardMaterial({color:0x010101,roughness:1});
const solids=[],items=[],lights=[];
function cube(name,x,y,z,w,h,d,mat,solid=false,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.name=name;o.position.set(x,y,z);o.castShadow=!mobile;o.receiveShadow=!mobile;parent.add(o);if(solid)solids.push({x,z,w,d});return o}
for(const z of [7,0,-7,-14,-21]){cube('floor',0,-.1,z,7.5,.2,7,F);cube('ceiling',0,3.5,z,7.5,.2,7,D)}
for(const z of [7,0,-7]){cube('wallL',-3.75,1.75,z,.2,3.5,7,W,true);cube('wallR',3.75,1.75,z,.2,3.5,7,W,true)}
for(const z of [-14,-21]){cube('wallL',-4.45,1.75,z,.2,3.5,7,W,true);cube('wallR',4.45,1.75,z,.2,3.5,7,W,true)}
cube('front',0,1.75,10.5,7.5,3.5,.2,W,true);cube('end',0,1.75,-24.5,9,3.5,.2,W,true);
function door(z,w=2.5){cube('doorTop',0,2.9,z,w+.4,.2,.3,WOOD);cube('doorL',-w/2,1.45,z,.18,2.9,.3,WOOD);cube('doorR',w/2,1.45,z,.18,2.9,.3,WOOD)}[3.5,-3.5,-10.5,-17.5].forEach(door);
cube('sofa',-2.2,.65,5.8,2.3,1.1,1.1,WOOD,true);cube('table',-2.1,.65,-1.7,2.3,1.1,1.1,WOOD,true);cube('wardrobe',2.2,1.4,-8.2,1.3,2.8,.8,WOOD,true);cube('bed',-2,.55,-15,3,.8,2,WOOD,true);cube('cabinet',2.1,1.35,-20.2,1.2,2.7,.8,WOOD,true);
for(const z of [7,0,-7,-14,-21]){const l=new THREE.PointLight(0xd2aa70,1.0,6);l.position.set(0,3,z);l.castShadow=!mobile;if(!mobile)l.shadow.mapSize.set(128,128);scene.add(l);lights.push(l);cube('bulb',0,3.08,z,.1,.1,.1,new THREE.MeshBasicMaterial({color:0xffd79c}))}
scene.add(new THREE.HemisphereLight(0x4a4742,0x030201,.28));
function makeItem(x,y,z,mat,type){const o=cube(type,x,y,z,.42,.42,.32,mat);o.userData.type=type;o.userData.baseY=y;items.push(o);return o}
const fuse=makeItem(2.2,1.65,5.7,METAL,'fuse');const key=makeItem(-2.1,1.25,-1.7,GOLD,'key');key.visible=false;const doll=makeItem(2.15,.8,-13.7,WOOD,'doll');doll.visible=false;const exit=cube('exit',0,1.5,-24.15,2.5,3,.2,BLACK);exit.userData.type='exit';items.push(exit);
const watcher=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.8,2.4,.5),BLACK);body.position.y=1.2;watcher.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.4,10,8),BLACK);head.position.y=2.6;watcher.add(head);for(const x of [-.14,.14]){const e=new THREE.Mesh(new THREE.SphereGeometry(.045,6,6),new THREE.MeshBasicMaterial({color:0xffffff}));e.position.set(x,2.64,-.36);watcher.add(e)}scene.add(watcher);watcher.visible=false;
const target=new THREE.Object3D();target.position.set(0,0,-15);cam.add(target);const flash=new THREE.SpotLight(0xfff4dc,7,20,Math.PI/7,.6,1.2);flash.castShadow=!mobile;if(!mobile)flash.shadow.mapSize.set(256,256);cam.add(flash);flash.target=target;scene.add(cam);
const ray=new THREE.Raycaster(),center=new THREE.Vector2(0,0);
function hud(force=false){const now=performance.now();if(!force&&now-lastHud<150)return;lastHud=now;const f=Math.round(g.fear),b=Math.round(g.battery);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=b+'%';$('objective').textContent=!g.fuse?'Find the fuse.':!g.key?'Find the house key.':!g.doll?'Find the watcher doll.':'Escape through the front door.';$('inventory').textContent=g.doll?'WATCHER DOLL':g.key?'HOUSE KEY':g.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',g.fuse],['checkKey',g.key],['checkDoll',g.doll],['checkEscape',g.win]].forEach(([id,v])=>$(id)?.classList.toggle('done',v));}
function msg(t){const s=$('status');if(s){s.textContent=t;clearTimeout(msg.t);msg.t=setTimeout(()=>s.textContent='READY',1800)}}
function flashlight(on){g.light=!!on&&g.battery>0;flash.visible=g.light}
function start(){if(g.start)return;g.start=true;$('boot').classList.add('hidden');flashlight(true);msg('Find the fuse.');hud(true)}
$('startBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();start()});
function blocked(x,z){if(x<-3.35||x>3.35)return true;for(const c of solids){if(x>c.x-c.w/2-.28&&x<c.x+c.w/2+.28&&z>c.z-c.d/2-.28&&z<c.z+c.d/2+.28)return true}return false}
function move(dt){if(!g.start||g.dead||g.win)return;let x=(keys.d?1:0)-(keys.a?1:0)+(keys.arrowright?1:0)-(keys.arrowleft?1:0)+joy.x;let z=(keys.s?1:0)-(keys.w?1:0)+(keys.arrowdown?1:0)-(keys.arrowup?1:0);const n=Math.hypot(x,z);if(n<.05){g.stamina=Math.min(100,g.stamina+dt*24);return}x/=n;z/=n;const sprint=g.run&&g.stamina>1;const speed=sprint?4.6:2.35;if(sprint)g.stamina=Math.max(0,g.stamina-dt*34);else g.stamina=Math.min(100,g.stamina+dt*20);const dx=(Math.cos(yaw)*x+Math.sin(yaw)*z)*speed*dt,dz=(-Math.sin(yaw)*x+Math.cos(yaw)*z)*speed*dt;const nx=cam.position.x+dx,nz=cam.position.z+dz;if(!blocked(nx,cam.position.z))cam.position.x=nx;if(!blocked(cam.position.x,nz))cam.position.z=nz;g.zone=Math.max(0,Math.min(4,Math.floor((8-cam.position.z)/7)))}
function interact(){if(!g.start||g.dead||g.win)return;ray.setFromCamera(center,cam);const hit=ray.intersectObjects(items,false).find(v=>v.distance<3.2);if(!hit){msg('Look directly at something.');return}const t=hit.object.userData.type;if(t==='fuse'&&!g.fuse){g.fuse=true;fuse.visible=false;key.visible=true;watcher.visible=true;watcher.position.set(-2,1,-1);g.fear=Math.min(100,g.fear+10);lights.forEach(l=>l.intensity=.55);msg('POWER RESTORED. Something moved.')}else if(t==='key'&&g.fuse&&!g.key){g.key=true;key.visible=false;doll.visible=true;watcher.visible=false;g.fear=Math.min(100,g.fear+12);msg('THE KEY WAS MOVED. Find the doll.')}else if(t==='doll'&&g.key&&!g.doll){g.doll=true;doll.visible=false;watcher.visible=true;watcher.position.set(0,1,-18);g.fear=Math.min(100,g.fear+20);msg('RUN. THE FRONT DOOR IS OPEN.')}else if(t==='exit'&&g.fuse&&g.key&&g.doll){g.win=true;$('win').classList.remove('hidden');msg('YOU ESCAPED.')}else if(t==='exit')msg('Locked. Find everything first.');hud(true)}
function toggleLight(){if(!g.start||g.dead)return;if(g.light){flashlight(false);msg('FLASHLIGHT OFF')}else if(g.battery>0){flashlight(true);msg('FLASHLIGHT ON')}else msg('BATTERY EMPTY')}
function ai(dt,now){if(!watcher.visible)return;const dx=cam.position.x-watcher.position.x,dz=cam.position.z-watcher.position.z,d=Math.hypot(dx,dz);if(d>0.01)watcher.rotation.y=Math.atan2(dx,dz);if(!g.doll){if(d<4.5&&now-lastAi>3500){g.fear=Math.min(100,g.fear+8);lastAi=now;msg('DON’T TURN AROUND.')}return}if(d>1.15){const step=Math.min(d-.8,dt*(g.run?1.7:1.25));watcher.position.x+=dx/d*step;watcher.position.z+=dz/d*step}if(d<3.2)g.fear=Math.min(100,g.fear+dt*(d<1.8?13:5));if(d<1){g.dead=true;$('death').classList.remove('hidden');msg('IT FOUND YOU')}}
function tick(now){const dt=Math.min(.045,(now-last)/1000);last=now;if(g.start&&!g.dead&&!g.win){move(dt);if(g.light){g.battery=Math.max(0,g.battery-dt*.85);if(g.battery<=0){flashlight(false);msg('FLASHLIGHT BATTERY EMPTY')}}ai(dt,now);if(g.fuse)g.fear=Math.min(100,g.fear+dt*.008);if(g.fear>=100){g.dead=true;$('death').classList.remove('hidden')}}if(g.start&&g.light&&mobile&&Math.random()<dt*.25)shake=.015;shake=Math.max(0,shake-dt*.04);cam.position.y=1.62+shake*(Math.random()-.5);hud();renderer.render(scene,cam);requestAnimationFrame(tick)}
addEventListener('keydown',e=>{const q=e.key.toLowerCase();keys[q]=true;if(q==='f')toggleLight();if(q==='e'||q==='enter')interact();if(q==='shift')g.run=true});addEventListener('keyup',e=>{const q=e.key.toLowerCase();keys[q]=false;if(q==='shift')g.run=false});
function runHold(id){const b=$(id);if(!b)return;const down=e=>{e.preventDefault();g.run=true;b.setPointerCapture?.(e.pointerId)},up=e=>{e.preventDefault();g.run=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up)}
runHold('runBtn');$('lightBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();toggleLight()});$('interactBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});$('retryBtn')?.addEventListener('pointerdown',()=>location.reload());$('againBtn')?.addEventListener('pointerdown',()=>location.reload());
const base=$('joystick'),stick=$('stick');let joyPointer=null;function resetJoy(){joy.x=0;joy.y=0;if(stick)stick.style.transform='translate(-50%,-50%)'}if(base&&stick){base.addEventListener('pointerdown',e=>{e.preventDefault();joyPointer=e.pointerId;base.setPointerCapture(e.pointerId);updateJoy(e)});base.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)updateJoy(e)});base.addEventListener('pointerup',e=>{if(e.pointerId===joyPointer){joyPointer=null;resetJoy()}});base.addEventListener('pointercancel',e=>{if(e.pointerId===joyPointer){joyPointer=null;resetJoy()}})}function updateJoy(e){const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy;const n=Math.hypot(dx,dy);if(n>max){dx=dx/n*max;dy=dy/n*max}joy.x=dx/max;joy.y=dy/max;stick.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}
renderer.domElement.addEventListener('pointerdown',e=>{if(!g.start||e.target.closest('button')||e.target.closest('#joystick'))return;look={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!look||e.pointerId!==look.id)return;yaw-=(e.clientX-look.x)*.004;pitch-=(e.clientY-look.y)*.004;pitch=Math.max(-1.15,Math.min(1.15,pitch));cam.rotation.set(pitch,yaw,0);look.x=e.clientX;look.y=e.clientY});renderer.domElement.addEventListener('pointerup',()=>look=null);renderer.domElement.addEventListener('pointercancel',()=>look=null);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.25))});hud(true);requestAnimationFrame(tick);