import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=id=>document.getElementById(id);
const g={start:false,fuse:false,key:false,doll:false,win:false,dead:false,light:true,battery:100,run:false,stamina:100,fear:8};
const k={};const joy={x:0,y:0};let yaw=0,pitch=0,look=null,last=performance.now(),scare=0;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020202);scene.fog=new THREE.Fog(0x080706,8,38);
const cam=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,70);cam.position.set(0,1.65,8.2);cam.rotation.order='YXZ';
const r=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});r.setSize(innerWidth,innerHeight);r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.shadowMap.enabled=true;r.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(r.domElement);
const W=new THREE.MeshStandardMaterial({color:0x25201b,roughness:1}),F=new THREE.MeshStandardMaterial({color:0x130d09,roughness:1}),D=new THREE.MeshStandardMaterial({color:0x080706,roughness:1}),WOOD=new THREE.MeshStandardMaterial({color:0x351b0d,roughness:.9}),METAL=new THREE.MeshStandardMaterial({color:0xc0beb5,metalness:.5,roughness:.3}),GOLD=new THREE.MeshStandardMaterial({color:0xc29b40,metalness:.5,roughness:.3}),BLACK=new THREE.MeshStandardMaterial({color:0x010101});
const solids=[],items=[];
function cube(n,x,y,z,w,h,d,m,solid=false){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.name=n;o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);if(solid)solids.push({x,z,w,d});return o}
for(const z of [7,0,-7,-14,-21]){cube('floor',0,-.1,z,7.5,.2,7,F);cube('ceiling',0,3.5,z,7.5,.2,7,D)}
for(const z of [7,0,-7]){cube('L',-3.75,1.75,z,.2,3.5,7,W,true);cube('R',3.75,1.75,z,.2,3.5,7,W,true)}
for(const z of [-14,-21]){cube('L',-4.5,1.75,z,.2,3.5,7,W,true);cube('R',4.5,1.75,z,.2,3.5,7,W,true)}
cube('front',0,1.75,10.5,7.5,3.5,.2,W,true);cube('end',0,1.75,-24.5,9,3.5,.2,W,true);
function door(z,w=2.5){cube('top',0,2.9,z,w+.4,.2,.3,WOOD);cube('a',-w/2,1.45,z,.18,2.9,.3,WOOD);cube('b',w/2,1.45,z,.18,2.9,.3,WOOD)}[3.5,-3.5,-10.5,-17.5].forEach(z=>door(z));
cube('sofa',-2.2,.65,5.8,2.3,1.1,1.1,WOOD,true);cube('table',-2.1,.65,-1.7,2.3,1.1,1.1,WOOD,true);cube('wardrobe',2.2,1.4,-8.2,1.3,2.8,.8,WOOD,true);cube('bed',-2,.55,-15,3,.8,2,WOOD,true);
for(const z of [7,0,-7,-14,-21]){const l=new THREE.PointLight(0xd2aa70,1.1,6);l.position.set(0,3,z);l.castShadow=true;l.shadow.mapSize.set(256,256);scene.add(l);cube('bulb',0,3.08,z,.1,.1,.1,new THREE.MeshBasicMaterial({color:0xffd79c}))}scene.add(new THREE.HemisphereLight(0x49443e,0x010101,.25));
function item(x,y,z,m,type){const o=cube(type,x,y,z,.4,.4,.3,m);o.userData.type=type;items.push(o);return o}
const fuse=item(2.2,1.7,5.7,METAL,'fuse');const key=item(-2.1,1.25,-1.7,GOLD,'key');key.visible=false;const doll=item(2.15,.8,-13.7,WOOD,'doll');doll.visible=false;const exit=cube('exit',0,1.5,-24.15,2.5,3,.2,BLACK);exit.userData.type='exit';items.push(exit);
const watcher=new THREE.Group();const b=cube('body',0,1.2,0,.8,2.4,.5,BLACK);b.parent=watcher;const h=new THREE.Mesh(new THREE.SphereGeometry(.4,14,10),BLACK);h.position.y=2.6;watcher.add(h);[-.14,.14].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),new THREE.MeshBasicMaterial({color:0xffffff}));e.position.set(x,2.64,-.36);watcher.add(e)});scene.add(watcher);watcher.visible=false;
const flash=new THREE.SpotLight(0xfff4dc,8,22,Math.PI/7,.55,1.1),target=new THREE.Object3D();target.position.set(0,0,-15);cam.add(flash);cam.add(target);flash.target=target;flash.castShadow=true;flash.shadow.mapSize.set(512,512);scene.add(cam);
function hud(){const f=Math.round(g.fear);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=Math.round(g.battery)+'%';$('objective').textContent=!g.fuse?'Find the fuse.':!g.key?'Find the house key.':!g.doll?'Find the watcher doll.':'Escape through the front door.';$('inventory').textContent=g.doll?'WATCHER DOLL':g.key?'HOUSE KEY':g.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',g.fuse],['checkKey',g.key],['checkDoll',g.doll],['checkEscape',g.win]].forEach(([id,v])=>$(id)?.classList.toggle('done',v))}
function msg(t){if($('status')){$('status').textContent=t;clearTimeout(msg.t);msg.t=setTimeout(()=>$('status').textContent='READY',2200)}}
function flashlight(on){g.light=!!on&&g.battery>0;flash.visible=g.light}
function start(){if(g.start)return;g.start=true;$('boot').classList.add('hidden');flashlight(true);msg('Find the fuse.');hud()}
$('startBtn')?.addEventListener('click',start);$('startBtn')?.addEventListener('pointerup',e=>{e.preventDefault();start()});
function blocked(x,z){if(x<-3.35||x>3.35)return true;for(const c of solids){if(x>c.x-c.w/2-.28&&x<c.x+c.w/2+.28&&z>c.z-c.d/2-.28&&z<c.z+c.d/2+.28)return true}return false}
function move(dt){if(!g.start||g.dead||g.win)return;let x=(k.d?1:0)-(k.a?1:0)+(k.arrowright?1:0)-(k.arrowleft?1:0)+joy.x,z=(k.s?1:0)-(k.w?1:0)+(k.arrowdown?1:0)-(k.arrowup?1:0);const n=Math.hypot(x,z);if(n<.01){g.stamina=Math.min(100,g.stamina+dt*22);return}x/=n;z/=n;const sprint=g.run&&g.stamina>1.5;const speed=sprint?4.4:2.3;if(sprint)g.stamina=Math.max(0,g.stamina-dt*32);else g.stamina=Math.min(100,g.stamina+dt*19);const dx=(Math.cos(yaw)*x+Math.sin(yaw)*z)*speed*dt,dz=(-Math.sin(yaw)*x+Math.cos(yaw)*z)*speed*dt;const nx=cam.position.x+dx,nz=cam.position.z+dz;if(!blocked(nx,cam.position.z))cam.position.x=nx;if(!blocked(cam.position.x,nz))cam.position.z=nz}
function interact(){if(!g.start||g.dead||g.win)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),cam);const hit=ray.intersectObjects(items,false).find(v=>v.distance<3.3);if(!hit){msg('Look at an object and move closer.');return}const t=hit.object.userData.type;if(t==='fuse'&&!g.fuse){g.fuse=true;fuse.visible=false;key.visible=true;watcher.visible=true;watcher.position.set(-2,1,-1);g.fear+=10;msg('POWER RESTORED. Footsteps behind you.')}else if(t==='key'&&g.fuse&&!g.key){g.key=true;key.visible=false;doll.visible=true;watcher.visible=false;g.fear+=12;msg('The key moved. Find the doll.')}else if(t==='doll'&&g.key&&!g.doll){g.doll=true;doll.visible=false;watcher.visible=true;watcher.position.set(0,1,-18);g.fear+=20;msg('RUN TO THE FRONT DOOR.')}else if(t==='exit'&&g.fuse&&g.key&&g.doll){g.win=true;$('win').classList.remove('hidden');msg('YOU ESCAPED.')}else if(t==='exit')msg('The door is locked.');hud()}
function toggleLight(){if(!g.start||g.dead)return;if(g.light){flashlight(false);msg('FLASHLIGHT OFF')}else if(g.battery>0){flashlight(true);msg('FLASHLIGHT ON')}else msg('BATTERY EMPTY')}
function ai(dt,now){if(!watcher.visible)return;const dx=cam.position.x-watcher.position.x,dz=cam.position.z-watcher.position.z,d=Math.hypot(dx,dz);watcher.lookAt(cam.position.x,1.4,cam.position.z);if(!g.doll){if(d<4.5&&now-scare>4500){g.fear=Math.min(100,g.fear+8);scare=now;msg('Something is standing behind you.')}return}if(d>1.2){const s=Math.min(d,dt*(g.run?1:1.5));watcher.position.x+=dx/d*s;watcher.position.z+=dz/d*s}if(d<2.4)g.fear=Math.min(100,g.fear+dt*11);if(d<.95){g.dead=true;$('death').classList.remove('hidden');msg('IT FOUND YOU')}}
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(g.start&&!g.dead&&!g.win){move(dt);if(g.light){g.battery=Math.max(0,g.battery-dt*1.0);if(g.battery<=0){flashlight(false);msg('FLASHLIGHT BATTERY EMPTY')}}ai(dt,now);if(g.fuse)g.fear=Math.min(100,g.fear+dt*.01);if(g.fear>=100){g.dead=true;$('death').classList.remove('hidden')}}hud();r.render(scene,cam);requestAnimationFrame(tick)}
addEventListener('keydown',e=>{const q=e.key.toLowerCase();k[q]=true;if(q==='f')toggleLight();if(q==='e'||q==='enter')interact();if(q==='shift')g.run=true});addEventListener('keyup',e=>{const q=e.key.toLowerCase();k[q]=false;if(q==='shift')g.run=false});
function hold(id,on,off){const b=$(id);if(!b)return;const down=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);on()};const up=e=>{e.preventDefault();off()};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',off)}hold('up',()=>joy.y=-1,()=>{if(joy.y<0)joy.y=0});hold('down',()=>joy.y=1,()=>{if(joy.y>0)joy.y=0});hold('left',()=>joy.x=-1,()=>{if(joy.x<0)joy.x=0});hold('right',()=>joy.x=1,()=>{if(joy.x>0)joy.x=0});hold('runBtn',()=>g.run=true,()=>g.run=false);$('lightBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();toggleLight()});$('interactBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});$('retryBtn')?.addEventListener('click',()=>location.reload());$('againBtn')?.addEventListener('click',()=>location.reload());
r.domElement.addEventListener('pointerdown',e=>{if(!g.start||e.target.closest('button'))return;look={id:e.pointerId,x:e.clientX,y:e.clientY};r.domElement.setPointerCapture?.(e.pointerId)});r.domElement.addEventListener('pointermove',e=>{if(!look||e.pointerId!==look.id)return;yaw-=(e.clientX-look.x)*.0045;pitch-=(e.clientY-look.y)*.0045;pitch=Math.max(-1.2,Math.min(1.2,pitch));cam.rotation.set(pitch,yaw,0);look.x=e.clientX;look.y=e.clientY});r.domElement.addEventListener('pointerup',()=>look=null);r.domElement.addEventListener('pointercancel',()=>look=null);r.domElement.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)});hud();requestAnimationFrame(tick);