import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=id=>document.getElementById(id);
const G={started:false,fuse:false,key:false,doll:false,won:false,dead:false,fear:8,battery:100,flash:true,run:false,stamina:100,chapter:0};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x030303);scene.fog=new THREE.FogExp2(0x080604,.032);
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,100);camera.position.set(0,1.65,9.2);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const M={wall:new THREE.MeshStandardMaterial({color:0x24201c,roughness:1}),wood:new THREE.MeshStandardMaterial({color:0x2b170d,roughness:.9}),floor:new THREE.MeshStandardMaterial({color:0x15100c,roughness:1}),dark:new THREE.MeshStandardMaterial({color:0x080706,roughness:1}),cloth:new THREE.MeshStandardMaterial({color:0x332725,roughness:1}),metal:new THREE.MeshStandardMaterial({color:0xbab8ae,metalness:.55,roughness:.3}),gold:new THREE.MeshStandardMaterial({color:0xb59645,metalness:.45,roughness:.3})};
const solids=[],items=[];
function box(name,x,y,z,w,h,d,mat,solid=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.name=name;m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(solid)solids.push({x,z,w,d});return m}function wall(x,z,w,d){box('wall',x,1.75,z,w,3.5,d,M.wall,true)}
for(const z of [7,0,-7,-14,-21]){box('floor',0,-.1,z,8,.2,7,M.floor);box('ceiling',0,3.55,z,8,.2,7,M.dark)}
for(const z of [7,0,-7]){wall(-4.05,z,.2,7);wall(4.05,z,.2,7)}wall(-5.05,-14,.2,7);wall(5.05,-14,.2,7);wall(-5.05,-21,.2,7);wall(5.05,-21,.2,7);for(const z of [10.5,-10.5,-17.5])wall(0,z,8,.2);wall(-3,-3.5,2,.2);wall(3,-3.5,2,.2);wall(-3,-17.5,2,.2);wall(3,-17.5,2,.2);
function frame(z,w=2.5){box('header',0,2.85,z,w+.4,.25,.3,M.wood);box('left',-w/2,1.45,z,.18,2.9,.3,M.wood);box('right',w/2,1.45,z,.18,2.9,.3,M.wood)}for(const z of [3.5,-3.5,-10.5,-17.5])frame(z,z===-17.5?3:2.5);
for(const z of [7,0,-7,-14,-21]){const l=new THREE.PointLight(0xd6ae73,1.15,6.5);l.position.set(0,3.05,z);l.castShadow=true;l.shadow.mapSize.set(256,256);scene.add(l);box('bulb',0,3.08,z,.1,.1,.1,new THREE.MeshBasicMaterial({color:0xffd99b}))}
box('sofa',-2.25,.65,5,2.4,1.1,1.15,M.cloth,true);box('cabinet',2.3,1.2,1,1.1,2.4,.7,M.wood,true);box('table',-2.15,.65,-2,2.3,1.1,1.15,M.wood,true);box('wardrobe',2.25,1.4,-8.4,1.35,2.8,.85,M.wood,true);box('bed',-2,.55,-15.2,3.1,.8,2,M.cloth,true);box('desk',2.15,.7,-19.3,2.2,1.3,.85,M.wood,true);
function item(name,x,y,z,mat,kind){const o=box(name,x,y,z,.42,.42,.3,mat);o.userData.kind=kind;items.push(o);return o}const fuse=item('fuse',2.35,1.72,5.15,M.metal,'fuse');const key=item('key',-2.1,1.28,-2,M.gold,'key');const doll=item('doll',2.25,.78,-13.7,M.cloth,'doll');key.visible=false;doll.visible=false;const exit=box('exit',0,1.5,-24.48,2.4,3,.25,M.dark);exit.userData.kind='exit';items.push(exit);
const watcher=new THREE.Group();const body=box('body',0,1.25,0,.8,2.4,.5,M.dark);body.parent=watcher;const head=new THREE.Mesh(new THREE.SphereGeometry(.4,16,12),M.dark);head.position.y=2.58;watcher.add(head);for(const x of [-.14,.14]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),new THREE.MeshBasicMaterial({color:0xffffff}));eye.position.set(x,2.64,-.36);watcher.add(eye)}scene.add(watcher);watcher.visible=false;
const flashlight=new THREE.SpotLight(0xfff4dc,6,20,Math.PI/7,.55,1.2);const flashTarget=new THREE.Object3D();scene.add(flashTarget);scene.add(flashlight);flashlight.castShadow=true;flashlight.shadow.mapSize.set(512,512);scene.add(new THREE.HemisphereLight(0x4a4640,0x020202,.28));
const keys={},joy={x:0,y:0};let yaw=0,pitch=0,last=performance.now(),look=null,lastScare=0;const tmpDir=new THREE.Vector3();
function say(t){const e=$('status');if(!e)return;e.textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>e.textContent='READY',2200)}function setFlash(on){G.flash=on&&G.battery>0;flashlight.visible=G.flash}
function hud(){const f=Math.round(G.fear);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=Math.round(G.battery)+'%';$('objective').textContent=!G.fuse?'Find the fuse in the living room.':!G.key?'The house changed. Find the key.':!G.doll?'Something is watching. Find the doll.':'Escape through the front door.';$('inventory').textContent=G.doll?'WATCHER DOLL':G.key?'HOUSE KEY':G.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',G.fuse],['checkKey',G.key],['checkDoll',G.doll],['checkEscape',G.won]].forEach(([id,v])=>$(id)?.classList.toggle('done',v));const rb=$('runBtn');if(rb)rb.style.opacity=G.stamina>5?'1':'.45'}
function start(){if(G.started)return;G.started=true;$('boot').classList.add('hidden');say('The front door locks behind you. Find the fuse.');hud();renderer.domElement.focus()}$('startBtn')?.addEventListener('click',start);$('startBtn')?.addEventListener('pointerup',e=>{e.preventDefault();start()});
function blocked(x,z){if(x<-3.55||x>3.55)return true;for(const c of solids){const ax=c.x-c.w/2-.28,bx=c.x+c.w/2+.28,az=c.z-c.d/2-.28,bz=c.z+c.d/2+.28;if(x>ax&&x<bx&&z>az&&z<bz)return true}return false}
function move(dt){if(!G.started||G.dead||G.won)return;let sx=(keys.d?1:0)-(keys.a?1:0),sy=(keys.s?1:0)-(keys.w?1:0);sx+=joy.x;sy+=joy.y;if(Math.abs(sx)+Math.abs(sy)<.01){G.run=false;G.stamina=Math.min(100,G.stamina+dt*18);return}const mag=Math.hypot(sx,sy);sx/=mag;sy/=mag;const sprint=G.run&&G.stamina>3;const speed=sprint?4.25:2.35;if(sprint)G.stamina=Math.max(0,G.stamina-dt*30);else G.stamina=Math.min(100,G.stamina+dt*18);const dx=(Math.cos(yaw)*sx+Math.sin(yaw)*sy)*speed*dt,dz=(-Math.sin(yaw)*sx+Math.cos(yaw)*sy)*speed*dt;const nx=camera.position.x+dx,nz=camera.position.z+dz;if(!blocked(nx,camera.position.z))camera.position.x=nx;if(!blocked(camera.position.x,nz))camera.position.z=nz}
function interact(){if(!G.started||G.dead||G.won)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const h=ray.intersectObjects(items,false).find(v=>v.distance<3.4);if(!h){say('Nothing within reach.');return}const k=h.object.userData.kind;if(k==='fuse'&&!G.fuse){G.fuse=true;h.object.visible=false;G.chapter=1;G.fear+=10;key.visible=true;watcher.visible=true;watcher.position.set(-2,0,-.5);say('POWER RESTORED. Footsteps upstairs.')}else if(k==='key'&&G.fuse&&!G.key){G.key=true;h.object.visible=false;G.chapter=2;G.fear+=12;doll.visible=true;watcher.visible=false;say('The key was not here before.')}else if(k==='doll'&&G.key&&!G.doll){G.doll=true;h.object.visible=false;G.chapter=3;G.fear+=22;watcher.visible=true;watcher.position.set(0,0,-18);say('DO NOT LOOK BACK. RUN.')}else if(k==='exit'&&G.fuse&&G.key&&G.doll){G.won=true;$('win').classList.remove('hidden');say('YOU ESCAPED. THE HOUSE REMEMBERS.')}else if(k==='exit')say('The lock will not move yet.');hud()}
function toggleFlash(){if(!G.started||G.dead)return;const next=!G.flash;if(next&&G.battery<=0){say('The flashlight battery is empty.');return}setFlash(next);say(G.flash?'Flashlight ON.':'Flashlight OFF.')}
function watcherAI(dt,now){if(!watcher.visible)return;const dx=camera.position.x-watcher.position.x,dz=camera.position.z-watcher.position.z,dist=Math.hypot(dx,dz);watcher.lookAt(camera.position.x,1.35,camera.position.z);if(G.chapter<3){if(dist<4.5&&now-lastScare>5000){G.fear=Math.min(100,G.fear+9);lastScare=now;say('Something moved behind you.')}return}const speed=G.run?.95:1.45;if(dist>2){const s=Math.min(dist,dt*speed);watcher.position.x+=dx/dist*s;watcher.position.z+=dz/dist*s}if(dist<2.1)G.fear=Math.min(100,G.fear+dt*13);if(dist<1){G.dead=true;$('death').classList.remove('hidden');say('IT FOUND YOU.')}}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(G.started&&!G.dead&&!G.won){move(dt);if(G.flash){G.battery=Math.max(0,G.battery-dt*1.15);if(G.battery<=0){setFlash(false);say('FLASHLIGHT BATTERY EMPTY.')}}watcherAI(dt,now);if(G.fuse)G.fear=Math.min(100,G.fear+dt*.01);if(G.fear>=100){G.dead=true;$('death').classList.remove('hidden')}}camera.getWorldDirection(tmpDir);flashlight.position.copy(camera.position);flashTarget.position.copy(camera.position).addScaledVector(tmpDir,16);flashlight.target=flashTarget;hud();renderer.render(scene,camera);requestAnimationFrame(frame)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k==='f')toggleFlash();if(k==='e'||e.key==='enter')interact();if(k==='shift')G.run=true});addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys[k]=false;if(k==='shift')G.run=false});
function bindHold(id,on,off){const b=$(id);if(!b)return;const start=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);on()};const end=e=>{e.preventDefault();off()};b.addEventListener('pointerdown',start);b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('lostpointercapture',off)}bindHold('up',()=>joy.y=-1,()=>{if(joy.y<0)joy.y=0});bindHold('down',()=>joy.y=1,()=>{if(joy.y>0)joy.y=0});bindHold('left',()=>joy.x=-1,()=>{if(joy.x<0)joy.x=0});bindHold('right',()=>joy.x=1,()=>{if(joy.x>0)joy.x=0});bindHold('runBtn',()=>G.run=true,()=>G.run=false);$('lightBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();toggleFlash()});$('interactBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});$('retryBtn')?.addEventListener('click',()=>location.reload());$('againBtn')?.addEventListener('click',()=>location.reload());
renderer.domElement.addEventListener('pointerdown',e=>{if(!G.started||e.target.closest('button'))return;look={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!look)return;yaw-=(e.clientX-look.x)*.0045;pitch-=(e.clientY-look.y)*.0045;pitch=Math.max(-1.2,Math.min(1.2,pitch));camera.rotation.set(pitch,yaw,0);look={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',()=>look=null);renderer.domElement.addEventListener('pointercancel',()=>look=null);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});hud();requestAnimationFrame(frame);