const S={x:50,y:70,speed:1.15,run:1.9,fuse:false,key:false,doll:false,note:false,battery:false,lights:true,batteryLevel:100,fear:12,changed:false,entity:false,dead:false,escaped:false,hidden:false,started:false,keys:{}};
const $=id=>document.getElementById(id),scene=$('scene'),status=$('status'),objective=$('objective'),fear=$('fear'),fearBar=$('fearBar'),batteryBar=$('batteryBar'),inventory=$('inventory'),msg=$('message'),entity=$('entity'),whisper=$('whisper'),noise=$('noise'),heartbeat=$('heartbeat'),lightBtn=$('lightBtn');
const fuse=$('fuse'),key=$('key'),doll=$('doll'),note=$('note'),batteryItem=$('batteryItem'),exitDoor=$('exitDoor'),hiding=$('hidingSpot');
function say(t,ms=2400){msg.textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>msg.textContent='',ms)}
function checklist(){[['checkFuse',S.fuse],['checkKey',S.key],['checkDoll',S.doll],['checkEscape',S.escaped]].forEach(([id,done])=>$(id).classList.toggle('done',done));const ids=[!S.fuse?'checkFuse':!S.key?'checkKey':!S.doll?'checkDoll':'checkEscape'];document.querySelectorAll('.checklist>div').forEach(x=>x.classList.remove('active'));$(ids[0]).classList.add('active')}
function render(){fear.textContent=Math.round(S.fear)+'%';fearBar.style.width=Math.round(S.fear)+'%';batteryBar.style.width=Math.round(S.batteryLevel)+'%';inventory.textContent=S.doll?'WATCHER DOLL':S.key?'HOUSE KEY':S.fuse?'FUSE':'EMPTY HANDS';checklist()}
function near(tx,ty,r=10){return Math.hypot(S.x-tx,S.y-ty)<r}
function move(dx,dy){if(!S.started||S.dead||S.escaped||S.hidden)return;const n=Math.hypot(dx,dy)||1,mult=S.keys.shift?S.run:1;S.x=Math.max(8,Math.min(92,S.x+dx/n*S.speed*mult));S.y=Math.max(20,Math.min(84,S.y+dy/n*S.speed*mult));if(S.changed)S.fear=Math.min(100,S.fear+.035*mult);if(S.keys.shift&&S.fear>75)entity.classList.add('chase');render()}
function flashlight(){if(!S.started||S.dead)return;if(S.batteryLevel<=0){say('The flashlight is dead.',1600);return}S.lights=!S.lights;scene.classList.toggle('dark',!S.lights);lightBtn.textContent=S.lights?'🔦':'◐';say(S.lights?'The beam cuts through the dark.':'You turn the flashlight off.',1300)}
function objectiveText(){if(!S.fuse)objective.textContent='Find the fuse.';else if(!S.key)objective.textContent='Find the key.';else if(!S.doll)objective.textContent='Find the doll.';else objective.textContent='Escape the house.'}
function interact(){if(!S.started||S.dead||S.escaped)return;if(S.hidden){S.hidden=false;hiding.textContent='HIDE';say('You step out.');return}
 if(!S.fuse&&near(68,50,14)){S.fuse=true;fuse.textContent='✓';fuse.classList.add('collected');S.fear+=7;status.textContent='POWER RESTORED';objectiveText();say('The lights snap on. Something upstairs heard you.',2800);setTimeout(changeHouse,900);render();return}
 if(S.fuse&&!S.key&&near(30,63,15)){S.key=true;key.classList.add('hidden');S.fear+=8;objectiveText();say('The key is warm. It was moved recently.',2400);setTimeout(whisperEvent,600);render();return}
 if(S.key&&!S.doll&&near(58,49,14)){S.doll=true;doll.classList.add('hidden');S.fear+=14;objectiveText();say('The doll has no face.',2200);setTimeout(entityScare,700);render();return}
 if(!S.note&&near(74,59,13)){S.note=true;note.classList.add('hidden');S.fear+=5;say('NOTE: It learns the way you move.',2400);render();return}
 if(!S.battery&&near(24,61,12)){S.battery=true;batteryItem.classList.add('hidden');S.batteryLevel=100;say('Fresh batteries.',1600);render();return}
 if(S.fuse&&S.key&&S.doll&&near(50,53,20)){S.escaped=true;document.querySelector('.exit-door span').textContent='OPEN';status.textContent='YOU ESCAPED';objectiveText();entity.classList.remove('show','chase');$('win').classList.remove('hidden');render();return}
 if(near(67,53,14))say(S.changed?'The hallway is different every time you look away.':'The door will not open yet.');else say(!S.fuse?'Find the fuse.':'Keep moving. The house is listening.');render()}
function changeHouse(){if(S.changed)return;S.changed=true;scene.classList.add('changed');S.fear+=12;entity.classList.remove('show');entity.classList.add('show');say('THE HOUSE HAS CHANGED.',2600);setTimeout(()=>{key.classList.remove('hidden');status.textContent='A door moved. Find the key.';objectiveText();render()},1200)}
function whisperEvent(){const a=['DON’T TURN AROUND','I SAW YOU','HE IS HERE','RUN'];whisper.textContent=a[Math.floor(Math.random()*a.length)];whisper.classList.remove('show');void whisper.offsetWidth;whisper.classList.add('show');S.fear=Math.min(100,S.fear+6);render()}
function entityScare(){S.entity=true;S.fear=Math.min(100,S.fear+18);entity.classList.remove('chase');void entity.offsetWidth;entity.classList.add('show');heartbeat.classList.add('on');noise.classList.add('on');say('IT IS WATCHING YOU.',2300);setTimeout(()=>{entity.classList.remove('show');entity.classList.add('chase')},900);setTimeout(()=>{heartbeat.classList.remove('on');noise.classList.remove('on');status.textContent='RUN TO THE EXIT'},2200);render()}
function lose(){if(S.dead||S.escaped)return;S.dead=true;$('death').classList.remove('hidden');$('deathText').textContent=S.hidden?'It waited until you came out.':'You ran too loudly. The house found you.'}
function reset(){location.reload()}
function start(){S.started=true;$('boot').classList.add('hidden');say('Find the fuse. Stay together.',2600);render()}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();S.keys[k]=true;if(k==='f')flashlight();if(['e','enter'].includes(k))interact();if(k==='h'&&S.started&&!S.dead&&!S.escaped){S.hidden=!S.hidden;hiding.textContent=S.hidden?'EXIT HIDE':'HIDE';say(S.hidden?'You hold your breath.':'You step out.',1500)}});window.addEventListener('keyup',e=>S.keys[e.key.toLowerCase()]=false);
setInterval(()=>{let dx=0,dy=0;if(S.keys.w||S.keys.arrowup)dy--;if(S.keys.s||S.keys.arrowdown)dy++;if(S.keys.a||S.keys.arrowleft)dx--;if(S.keys.d||S.keys.arrowright)dx++;if(dx||dy)move(dx,dy)},30);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;const down=e=>{e.preventDefault();S.keys[k]=true};const up=e=>{e.preventDefault();S.keys[k]=false};['touchstart','mousedown'].forEach(x=>b.addEventListener(x,down,{passive:false}));['touchend','touchcancel','mouseup','mouseleave'].forEach(x=>b.addEventListener(x,up,{passive:false}))});
$('interactBtn').onclick=interact;lightBtn.onclick=flashlight;$('runBtn').onpointerdown=()=>S.keys.shift=true;$('runBtn').onpointerup=()=>S.keys.shift=false;$('runBtn').onpointercancel=()=>S.keys.shift=false;[fuse,key,doll,note,batteryItem,exitDoor,hiding].forEach(el=>el.addEventListener('click',interact));$('startBtn').onclick=start;$('retryBtn').onclick=reset;$('againBtn').onclick=reset;
setInterval(()=>{if(!S.started||S.dead||S.escaped)return;if(S.lights)S.batteryLevel=Math.max(0,S.batteryLevel-.09);if(S.changed){S.fear=Math.min(100,S.fear+(Math.random()<.22?.5:-.08));if(Math.random()<.045)whisperEvent()}if(S.fear>88&&!S.hidden&&Math.random()<.08)entityScare();if(S.fear>=100)lose();render()},1000);render();