import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id);
const state={started:false,dead:false,won:false,fear:12,battery:100,flash:true,fuse:false,key:false,doll:false,hidden:false,run:false,entityActive:false};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050504);scene.fog=new THREE.FogExp2(0x080705,.045);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,80);camera.position.set(0,1.65,7.5);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const clock=new THREE.Clock(),keys={},ray=new THREE.Raycaster();let yaw=0,pitch=0,lookTouch=null,joy={x:0,y:0};const colliders=[],interactables=[];
function mat(c,r=.75){return new THREE.MeshStandardMaterial({color:c,roughness:r});}function box(name,x,y,z,sx,sy,sz,m,solid=true){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),m);o.name=name;o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);if(solid)colliders.push({o,min:new THREE.Vector3(x-sx/2,y-sy/2,z-sz/2),max:new THREE.Vector3(x+sx/2,y+sy/2,z+sz/2)});return o;}
const wood=mat(0x2b1a12),darkWood=mat(0x120d09),wall=mat(0x2b2924),wall2=mat(0x211f1b),floorMat=mat(0x211610),rugMat=mat(0x3a241b);
box('floor',0,-.08,0,16,.16,28,floorMat,false);box('ceiling',0,3.55,0,16,.16,28,wall2,false);box('leftWall',-4,1.75,0,.22,3.6,28,wall);box('rightWall',4,1.75,0,.22,3.6,28,wall);box('rug',0,.035,0,2.8,.025,20,rugMat,false);
function doorway(z,side){const x=side<0?-3.84:3.84;box('frame',x,1.55,z,.3,3.1,2.1,darkWood);box('door',x+(side<0?.15:-.15),1.5,z,.12,2.8,1.75,wood,false)}for(let z=-10;z<=8;z+=4){doorway(z,-1);doorway(z,1)}box('farFrame',0,1.65,-12.8,3.2,3.3,.25,darkWood);box('farDoor',0,1.55,-12.62,2.7,2.9,.12,wood,false);
const lamps=[];for(let z=7;z>=-11;z-=6){const l=new THREE.PointLight(0xd8b98a,1.4,7,2);l.position.set(0,3.15,z);l.castShadow=true;l.shadow.mapSize.set(512,512);scene.add(l);lamps.push(l);const b=new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),new THREE.MeshBasicMaterial({color:0xffe5ad}));b.position.copy(l.position);scene.add(b)}
box('table',-2.7,.8,3.6,2.1,1.55,.9,wood);box('tableTop',-2.7,1.6,3.6,2.3,.14,1,mat(0x3a2418),false);const tableLamp=new THREE.PointLight(0xd79a52,2,4,2);tableLamp.position.set(-2.7,2.5,3.6);scene.add(tableLamp);
const exit=box('EXIT',0,1.6,-12.35,1.5,2.8,.12,darkWood,false);exit.userData.exit=true;interactables.push(exit);
function obj(name,pos,color,em=0){const o=new THREE.Mesh(new THREE.BoxGeometry(.34,.34,.22),new THREE.MeshStandardMaterial({color,roughness:.45,emissive:color,emissiveIntensity:em}));o.name=name;o.position.copy(pos);o.castShadow=true;scene.add(o);interactables.push(o);return o}const fuse=obj('fuse',new THREE.Vector3(1.8,1.55,2.8),0xd9d5ca,.15),key=obj('key',new THREE.Vector3(-2.2,1.25,-1.5),0xb99b50,.05),doll=obj('doll',new THREE.Vector3(1.4,.65,-7),0x2d2422,.02),note=obj('note',new THREE.Vector3(-3.65,1.3,6),0xc9bda5,.02),battery=obj('battery',new THREE.Vector3(2.9,1.1,5.5),0xaaa9a0,.08);key.visible=false;doll.visible=false;
const hide=box('hide',3.55,1.2,1.4,.6,2.2,1.2,darkWood);hide.userData.hide=true;interactables.push(hide);
const enemy=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.2,5,10),mat(0x050505));body.position.y=1.1;enemy.add(body);const eyeMat=new THREE.MeshBasicMaterial({color:0xffffff});for(const x of [-.13,.13]){const e=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),eyeMat);e.position.set(x,1.65,-.32);enemy.add(e)}enemy.position.set(0,0,-10);enemy.visible=false;scene.add(enemy);
const flash=new THREE.SpotLight(0xfff4dd,5,18,Math.PI/8,.55,1.3);camera.add(flash);camera.add(flash.target);scene.add(camera);scene.add(new THREE.HemisphereLight(0x5b5046,0x090807,.35));
function blocked(p){return colliders.some(c=>p.x>c.min.x-.25&&p.x<c.max.x+.25&&p.z>c.min.z-.25&&p.z<c.max.z+.25)}
function move(){if(!state.started||state.dead||state.won||state.hidden)return;let x=0,z=0;if(keys.w||keys.arrowup)z--;if(keys.s||keys.arrowdown)z++;if(keys.a||keys.arrowleft)x--;if(keys.d||keys.arrowright)x++;x+=joy.x;z+=joy.y;if(!x&&!z)return;const n=Math.hypot(x,z)||1;const speed=(state.run?3.6:2)*clock.getDelta();const forward=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),next=camera.position.clone().addScaledVector(forward,z/n*speed).addScaledVector(right,x/n*speed);next.y=1.65;if(!blocked(next))camera.position.copy(next)}
function updateHUD(){const f=Math.round(state.fear);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=Math.round(state.battery)+'%';$('objective').textContent=!state.fuse?'Find the fuse.':!state.key?'Find the key.':!state.doll?'Find the doll.':'Escape the house.';$('inventory').textContent=state.doll?'WATCHER DOLL':state.key?'HOUSE KEY':state.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',state.fuse],['checkKey',state.key],['checkDoll',state.doll],['checkEscape',state.won]].forEach(([id,on])=>$(id).classList.toggle('done',on))}
function say(t){$('message').textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>$('message').textContent='',2500)}
function interact(){if(!state.started||state.dead||state.won)return;if(state.hidden){state.hidden=false;say('You step out.');return}ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(interactables,true).find(h=>h.distance<3.2);if(!hit){say('Nothing here.');return}let o=hit.object;while(o.parent&&!interactables.includes(o))o=o.parent;if(o===fuse&&!state.fuse){state.fuse=true;fuse.visible=false;state.fear+=8;lamps.forEach(l=>l.intensity=2.2);say('The power returns. Something moved upstairs.');setTimeout(()=>{state.fear+=12;key.visible=true;enemy.visible=true;state.entityActive=true;say('THE HOUSE HAS CHANGED.')},900)}else if(o===key&&state.fuse&&!state.key){state.key=true;key.visible=false;state.fear+=8;say('The key is warm. It was moved recently.')}else if(o===doll&&state.key&&!state.doll){state.doll=true;doll.visible=false;state.fear+=18;enemy.visible=true;state.entityActive=true;enemy.position.set(0,0,-5);say('IT IS WATCHING YOU. RUN.')}else if(o===note){note.visible=false;state.fear+=4;say('NOTE: It learns how you move.')}else if(o===battery){battery.visible=false;state.battery=100;say('Fresh batteries.')}else if(o===hide){state.hidden=true;say('You hold your breath.')}else if(o===exit&&state.fuse&&state.key&&state.doll){state.won=true;$('win').classList.remove('hidden');say('You escaped. But it remembers you.')}else if(o===exit)say('LOCKED. Find everything first.');updateHUD()}
function flashlight(){if(!state.started||state.dead)return;if(state.battery<=0){say('The flashlight is dead.');return}state.flash=!state.flash;flash.intensity=state.flash?5:0;$('lightBtn').classList.toggle('off',!state.flash);say(state.flash?'The beam cuts through the dark.':'You switch the flashlight off.')}
function scare(dt){if(!state.entityActive||state.dead||state.won||state.hidden)return;const target=camera.position.clone();target.y=0;const ep=enemy.position.clone();ep.y=0;const d=target.distanceTo(ep);if(d<8){state.fear=Math.min(100,state.fear+dt*7);enemy.lookAt(camera.position.x,1.2,camera.position.z);enemy.position.lerp(target,.035*dt*2);if(d<1.25){state.dead=true;$('death').classList.remove('hidden');$('deathText').textContent='It learned your route.'}}}
function update(){const dt=Math.min(clock.getDelta(),.05);move();if(state.started&&!state.dead&&!state.won){if(state.flash)state.battery=Math.max(0,state.battery-dt*.9);if(state.fuse)state.fear=Math.max(0,state.fear-dt*.25);if(Math.random()<dt*.07&&state.fuse)state.fear=Math.min(100,state.fear+1.5);scare(dt);if(state.fear>=100){state.dead=true;$('death').classList.remove('hidden');$('deathText').textContent='The house swallowed the light.'}}flash.position.copy(camera.position);flash.target.position.copy(camera.position).add(new THREE.Vector3(Math.sin(yaw),-.05,-Math.cos(yaw)).multiplyScalar(5));updateHUD();renderer.render(scene,camera);requestAnimationFrame(update)}
function start(){if(state.started)return;state.started=true;$('boot').classList.add('hidden');say('Find the fuse. Stay together.');updateHUD()}
window.startGame=start;window.addEventListener('house-start',start);window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k==='f')flashlight();if(k==='e'||e.key==='Enter')interact();if(k==='shift')state.run=true;if(k==='h'){state.hidden=!state.hidden;say(state.hidden?'You hide.':'You step out.')}});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.key.toLowerCase()==='shift')state.run=false});
renderer.domElement.addEventListener('click',()=>{if(state.started&&innerWidth>700)renderer.domElement.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0022;pitch-=e.movementY*.0022;pitch=Math.max(-1.35,Math.min(1.35,pitch));camera.rotation.set(pitch,yaw,0)}});
function touchLook(e){if(e.target.closest('button'))return;if(!lookTouch){lookTouch={x:e.touches[0].clientX,y:e.touches[0].clientY};return}const t=e.touches[0];yaw-=(t.clientX-lookTouch.x)*.004;pitch-=(t.clientY-lookTouch.y)*.004;pitch=Math.max(-1.25,Math.min(1.25,pitch));camera.rotation.set(pitch,yaw,0);lookTouch={x:t.clientX,y:t.clientY)}
renderer.domElement.addEventListener('touchstart',e=>{if(state.started)lookTouch={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});renderer.domElement.addEventListener('touchmove',e=>{if(state.started)touchLook(e)},{passive:true});renderer.domElement.addEventListener('touchend',()=>lookTouch=null);
function bindHold(id,dx,dy){const b=$(id),on=e=>{e.preventDefault();joy.x=dx;joy.y=dy},off=e=>{e.preventDefault();joy.x=0;joy.y=0};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)}bindHold('up',0,-1);bindHold('down',0,1);bindHold('left',-1,0);bindHold('right',1,0);$('startBtn').addEventListener('click',start);$('lightBtn').addEventListener('click',flashlight);$('interactBtn').addEventListener('click',interact);$('runBtn').addEventListener('pointerdown',()=>state.run=true);$('runBtn').addEventListener('pointerup',()=>state.run=false);$('runBtn').addEventListener('pointercancel',()=>state.run=false);$('retryBtn').addEventListener('click',()=>location.reload());$('againBtn').addEventListener('click',()=>location.reload());window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5))});updateHUD();update();