import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=id=>document.getElementById(id);const S={started:false,fuse:false,key:false,doll:false,fear:12,battery:100,flash:true,run:false,dead:false,won:false};
const world=new THREE.Scene();world.background=new THREE.Color(0x050504);world.fog=new THREE.Fog(0x070605,5,28);
const cam=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,60);cam.position.set(0,1.65,7);cam.rotation.order='YXZ';
const gl=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});gl.setSize(innerWidth,innerHeight);gl.setPixelRatio(Math.min(devicePixelRatio,1.5));gl.shadowMap.enabled=true;gl.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(gl.domElement);
const mats={wall:new THREE.MeshStandardMaterial({color:0x292722,roughness:1}),wood:new THREE.MeshStandardMaterial({color:0x2b1911,roughness:.85}),floor:new THREE.MeshStandardMaterial({color:0x211611,roughness:.95}),dark:new THREE.MeshStandardMaterial({color:0x090807,roughness:1}),red:new THREE.MeshStandardMaterial({color:0x651015,roughness:.8})};
const solids=[];const items=[];
function cube(name,p,s,m,solid=false){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.name=name;o.position.set(...p);o.castShadow=true;o.receiveShadow=true;world.add(o);if(solid)solids.push([p,s]);return o}
cube('floor',[0,-.1,0],[12,.2,28],mats.floor);cube('left',[-4,1.8,0],[.2,3.6,28],mats.wall,true);cube('right',[4,1.8,0],[.2,3.6,28],mats.wall,true);cube('ceiling',[0,3.6,0],[12,.2,28],mats.dark);
for(let z=8;z>-13;z-=4){cube('doorL',[-3.82,1.45,z],[.12,2.7,1.8],mats.wood);cube('doorR',[3.82,1.45,z],[.12,2.7,1.8],mats.wood)}cube('far',[0,1.5,-12.7],[2.8,2.9,.15],mats.wood);
const rug=cube('rug',[0,.02,0],[2.8,.03,19],new THREE.MeshStandardMaterial({color:0x39231a,roughness:1}));
for(let z=7;z>-12;z-=6){const l=new THREE.PointLight(0xe0bd8b,1.8,7,2);l.position.set(0,3.1,z);l.castShadow=true;l.shadow.mapSize.set(512,512);world.add(l);cube('bulb',[0,3.08,z],[.12,.12,.12],new THREE.MeshBasicMaterial({color:0xffe3b0}))}
const table=cube('table',[-2.7,.8,4],[2,1.5,.9],mats.wood,true);const tl=new THREE.PointLight(0xc77e3e,2.2,4);tl.position.set(-2.7,2.5,4);world.add(tl);
function item(name,p,c){const o=cube(name,p,[.35,.35,.25],new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.12}));items.push(o);return o}
const fuse=item('fuse',[1.8,1.5,2.8],0xe0ddd3),key=item('key',[-2,1.2,-1.5],0xb99b50),doll=item('doll',[1.3,.7,-7],0x332824);key.visible=doll.visible=false;
const exit=cube('exit',[0,1.5,-12.5],[1.7,2.9,.12],mats.dark);items.push(exit);
const enemy=new THREE.Group();enemy.add(cube('body',[0,1.1,0],[.7,2,.55],mats.dark));for(const x of [-.13,.13]){const e=new THREE.Mesh(new THREE.SphereGeometry(.055,8,8),new THREE.MeshBasicMaterial({color:0xffffff}));e.position.set(x,1.65,-.3);enemy.add(e)}enemy.position.set(0,0,-9);enemy.visible=false;world.add(enemy);
const light=new THREE.SpotLight(0xfff4dd,5,18,Math.PI/7,.5,1.4);cam.add(light);cam.add(light.target);world.add(cam);world.add(new THREE.HemisphereLight(0x5c5148,0x080706,.4));
const keys={},joy={x:0,y:0};let yaw=0,pitch=0,last=performance.now(),touch=null;
function hud(){const f=Math.round(S.fear);$('fear').textContent=f+'%';$('fearBar').style.width=f+'%';$('batteryBar').style.width=Math.round(S.battery)+'%';$('objective').textContent=!S.fuse?'Find the fuse.':!S.key?'Find the key.':!S.doll?'Find the doll.':'Escape the house.';$('inventory').textContent=S.doll?'WATCHER DOLL':S.key?'HOUSE KEY':S.fuse?'FUSE':'EMPTY HANDS';[['checkFuse',S.fuse],['checkKey',S.key],['checkDoll',S.doll],['checkEscape',S.won]].forEach(([i,v])=>$(i)?.classList.toggle('done',v))}
function say(t){$('status').textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>{$('status').textContent='READY'},2200)}
function start(){if(S.started)return;S.started=true;$('boot').classList.add('hidden');say('Find the fuse. Stay together.');hud()}
window.startGame=start;window.addEventListener('house-start',start);$('startBtn').addEventListener('click',start);$('startBtn').addEventListener('pointerup',e=>{e.preventDefault();start()});$('startBtn').addEventListener('touchend',e=>{e.preventDefault();start()},{passive:false});
function move(dt){if(!S.started||S.dead||S.won)return;let x=(keys.a?-1:0)+(keys.d?1:0)+joy.x,z=(keys.w?-1:0)+(keys.s?1:0)+joy.y;if(!x&&!z)return;const n=Math.hypot(x,z),v=(S.run?3.6:2)*dt;const nx=cam.position.x+(Math.cos(yaw)*x/n+Math.sin(yaw)*z/n)*v;const nz=cam.position.z+(-Math.sin(yaw)*x/n+Math.cos(yaw)*z/n)*v;if(Math.abs(nx)<3.65&&nz>-12.2&&nz<12.2){cam.position.x=nx;cam.position.z=nz}}
function interact(){if(!S.started||S.dead||S.won)return;const r=new THREE.Raycaster();r.setFromCamera(new THREE.Vector2(0,0),cam);const h=r.intersectObjects(items,false).find(v=>v.distance<3.3);if(!h){say('Nothing here.');return}const o=h.object;if(o===fuse&&!S.fuse){S.fuse=true;fuse.visible=false;S.fear+=8;key.visible=true;enemy.visible=true;enemy.position.set(0,0,-9);say('POWER RESTORED — something heard you.')}else if(o===key&&S.fuse&&!S.key){S.key=true;key.visible=false;S.fear+=8;doll.visible=true;say('The key is warm.')}else if(o===doll&&S.key&&!S.doll){S.doll=true;doll.visible=false;S.fear+=18;enemy.position.set(0,0,-4);say('IT IS WATCHING YOU. RUN.')}else if(o===exit&&S.fuse&&S.key&&S.doll){S.won=true;$('win').classList.remove('hidden');say('YOU ESCAPED.')}else if(o===exit)say('LOCKED — find everything first.');hud()}
function flashlight(){if(!S.started||S.dead)return;S.flash=!S.flash;light.intensity=S.flash?5:0;say(S.flash?'Flashlight on.':'Flashlight off.')}function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;move(dt);if(S.started&&!S.dead&&!S.won){if(S.flash)S.battery=Math.max(0,S.battery-dt*.8);if(S.fuse)S.fear=Math.min(100,S.fear+dt*.03);if(enemy.visible){enemy.lookAt(cam.position.x,1.1,cam.position.z);enemy.position.lerp(new THREE.Vector3(cam.position.x,0,cam.position.z),dt*.018);if(enemy.position.distanceTo(cam.position)<1.1){S.dead=true;$('death').classList.remove('hidden');}}if(S.fear>=100){S.dead=true;$('death').classList.remove('hidden')}}light.position.copy(cam.position);light.target.position.copy(cam.position).add(new THREE.Vector3(-Math.sin(yaw),-.05,-Math.cos(yaw)).multiplyScalar(5));hud();gl.render(world,cam);requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k==='f')flashlight();if(k==='e'||e.key==='Enter')interact();if(k==='shift')S.run=true});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.key.toLowerCase()==='shift')S.run=false});
function bind(id,x,y){const b=$(id);const on=e=>{e.preventDefault();joy.x=x;joy.y=y};const off=e=>{e.preventDefault();joy.x=0;joy.y=0};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)}bind('up',0,-1);bind('down',0,1);bind('left',-1,0);bind('right',1,0);$('lightBtn').addEventListener('click',flashlight);$('interactBtn').addEventListener('click',interact);$('runBtn').addEventListener('pointerdown',()=>S.run=true);$('runBtn').addEventListener('pointerup',()=>S.run=false);$('retryBtn').addEventListener('click',()=>location.reload());$('againBtn').addEventListener('click',()=>location.reload());gl.domElement.addEventListener('touchstart',e=>{if(!S.started||e.target.closest('button'))return;touch={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});gl.domElement.addEventListener('touchmove',e=>{if(!touch)return;const t=e.touches[0];yaw-=(t.clientX-touch.x)*.004;pitch-=(t.clientY-touch.y)*.004;pitch=Math.max(-1.2,Math.min(1.2,pitch));cam.rotation.set(pitch,yaw,0);touch={x:t.clientX,y:t.clientY}},{passive:true});gl.domElement.addEventListener('touchend',()=>touch=null);window.addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();gl.setSize(innerWidth,innerHeight)});hud();requestAnimationFrame(frame);